spring:
  jpa:
    database: default
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:sqlserver://172.23.16.13;databaseName=BD_GEVERANDES;ApplicationName=tpp-core-app-maestros;encrypt=true;trustServerCertificate=true
    username: userdevcliente
    password: U5erD3vCL15nt3
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  output:
    ansi:
      enabled: "ALWAYS"
  main:
    banner-mode: "off"    
  
server:
  port: 6061
springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      base-path: /api
      exposure:
        include: health,info,refresh
      path-mapping:
        info: status

logging:
  level:
    '[pe.com.tpp.documentacion]': INFO
    '[org.springframework.boot.actuate.endpoint.invoker.cache]': TRACE
  config: classpath:logback.xml
